### ISSUE TITLE
Introduction article

### ISSUE THREAD

**Issue by tima101** [async-labs/saas#10]
Write an Introduction article

<details>
      <summary>Click to see <b>Hill for issue #10</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/10.png" alt="Single issue hill" class="s3-image"/></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image"/></div></details>
      
created by [Async](https://async-await.com/)

**Comment by Feelthewind** [comment]
Whare is the introduction article? I want to know how to make this one. Thank you.
