### ISSUE TITLE
Ch 1, random aaa attached to words in different sections.

### ISSUE THREAD

**Issue by ElijahElrod** [async-labs/saas#102]
ESLint, Prettier: existingaaa
Next.js: Custom App: allaaa
Testing: changeaaa
Production-server folder section under testing: additionaaa
When talking about the sourceMap, and compilation process: noaaa
End of chapter when talking about GA_TRACKING_ID: There is a universallyaaa & notaaa

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #102</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/102.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by ElijahElrod** [comment]
This actually happens in most of the chapters as I ctrl-f and look for them

**Comment by klyburke** [comment]
Thanks @tima101 ! Done.
