### ISSUE TITLE
Critical security issue in one node dependency: event-stream

### ISSUE THREAD

**Issue by Murillo2380** [async-labs/saas#11]
Hello. 

I'm not able to try this repository locally. Looks like there is a problem to install the node packages running the yarn command.

After running `yarn` in the api folder, the following error appears:

```
error https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Extracting tar content of undefined failed, thefile appears to be corrupt: "Unexpected end of data"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Looks like it has something to do about this problem: https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident

It can be checked by running the following command inside api folder: `yarn audit`

What do to?

**Comment by Murillo2380** [comment]
I guess I just had to remove and add the nodemon package again.

Old dependency in package.json:
`"nodemon": "^1.18.4"`

New dependency:
"nodemon": "^1.18.9"

Source: https://github.com/remy/nodemon/commit/21e052eddf144b27a7c0eb9c603236707003d75d

**Comment by tima101** [comment]
@Murillo2380 Please check up: https://github.com/eclipse/che/issues/12077#issuecomment-443208053
