### ISSUE TITLE
have subdomain for each team ?

### ISSUE THREAD

**Issue by kerituni12** [async-labs/saas#111]
ex: team1.builderbook.org

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #111</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/111.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by tima101** [comment]
@kerituni12 No plans to implement it in this boilerplate but you are welcome to implement it in your own project or public repo.
