### ISSUE TITLE
Not showing up on my browser

### ISSUE THREAD

**Issue by mrhanson3** [async-labs/saas#113]
![Screen Shot 2020-09-08 at 4 15 46 PM](https://user-images.githubusercontent.com/20564536/92523608-a884b000-f1ee-11ea-9ad1-8d38857af27b.png)

Everything appears to be in good running order, but nothing is showing up on my http://localhost:3000/, does anyone have any idea what could be going on? I'm working on Ch. 4 and I used the code from the end of the book, beyond adding my env info for MongoDB. 

This is in both of my .env files. 

URL_APP=http://localhost:3000
URL_API=http://localhost:8000

**Comment by mrhanson3** [comment]
I rolled it back to the last working version, and it runs, but if anyone knows what happened, I'm curious.

**Comment by tima101** [comment]
@mrhanson3 What is "last working version"? You can create public repo and share it with me with **exact** code that have problem.

**Comment by mrhanson3** [comment]
I meant the last version that I pushed to Github. I'm having a rough time making this project work, so I'm going to take a few weeks off and maybe come back to it. I appreciate the offer to help though.

**Comment by tima101** [comment]
@mrhanson3 No problem. Let us know how it goes. I am happy to look at your exact codebase that throws error.

**Comment by tima101** [comment]
@mrhanson3 Would you please try this suggestion: https://github.com/async-labs/saas/issues/114#issuecomment-690369562
