### ISSUE TITLE
book/3-begin "Problem loading page"

### ISSUE THREAD

**Issue by andrewshrout** [async-labs/saas#114]
**Expected behavior**
Book 3, section "App Server". 
`Once you are done, we are ready to test the code we wrote in Step 1 and Step 2.

Start your app with yarn dev and navigate to http://localhost:3000:`

Expected to run yarn dev, and find "Error: Not Found" like the book says due to this line throw new Error(response.statusText);

Or after changing to "throw new Error(response.status.toString());" to find Error: 404

**Book/3-end Expected Behavior**

enter /app -> 'yarn dev' -> have some website infront of me

**Actual behavior**
[https://imgur.com/a/oHsZJzE](url)

"Unable to connect

Firefox can’t establish a connection to the server at localhost:3000."

This is in both situations.

**Information about the Issue**
Even after restarting my linux system, or triple checking to make sure that it was using the right internet / ports in my virtual box, I can't figure out whats going on here. Previous two books worked. The only files I "changed" was the ones mentioned in the book up until this point in book 3 

EDIT: Confirmed the same effect on book 4, and that it is the same on windows.

- book/3-begin/app/lib/api/sendRequestAndGetResponse.ts

**Steps to reproduce the behavior**

1. https://github.com/andrewshrout/saas-book-course
2. enter either folder and run "yarn dev"
3. https://imgur.com/a/8otgFN0 it compiles
4. Receive local host error.

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #114</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/114.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by tima101** [comment]
@andrewshrout I ran apps, please check your `.env` file and see if it has:
```
URL_APP=http://localhost:3000
PORT_APP=3000
```

I am gonna check chapter's content and make sure that ask reader to have the above two env variables.

An important note, for `book/3-end` project and all downstream chapters you have to run `APP` and `API` projects at the same time since `APP` on browser or server sends requests to `API`.

**Comment by tima101** [comment]
@andrewshrout Nice. I added a reminder to the content. 

---

> TypeError: Request with GET/HEAD method cannot have body

Please share link to the exact codebase and I will try to reproduce

**Comment by andrewshrout** [comment]
https://github.com/andrewshrout/saas-book-course/tree/master/book/3-begin

@tima101 just go to book 3 and yarn dev. 

Sorry to be so troublesome. I appreciate the new reminder + how my console should look after yarn dev'ing.

Something must be happening on the server because my console isn't printing the req.body, or the "localhost:3000/api/v1/public/get-user"

**Comment by tima101** [comment]
@andrewshrout Please do send us feedback, sometimes we do need to add a fix.

Try following fixes to your above problem.

Replace:
```
  const response = await fetch(
    `${path}${qs}`,
    Object.assign({ method: 'POST', credentials: 'include' }, opts, { headers }),
  );
```

With:
```
  const response = await fetch(
    `${process.env.URL_APP}${path}${qs}`,
    Object.assign({ method: 'POST', credentials: 'include' }, opts, { headers }),
  );
```

Replace:
```
export const getUser = (options = {}) =>
  sendRequestAndGetResponse(
    `${BASE_PATH}/get-user`,
    Object.assign(
      {
        method: 'GET',
      },
      options,
    ),
  );
```

With:
```
export const getUser = (request) =>
  sendRequestAndGetResponse(`${BASE_PATH}/get-user`, {
    request,
    method: 'GET',
  });
```

And finally, replace:
```
  server.get('/api/v1/public/get-user', (req, res) => {
    console.log(req.body);
    res.json({ user: { email: 'team@builderbook.org' } });
  });
```

With:
```
  server.get('/api/v1/public/get-user', (_, res) => {
    console.log('Express route /get-user');
    res.json({ user: { email: 'team@builderbook.org' } });
  });
```

Please let me know how it goes. I am adding fixes to the content.

**Comment by tima101** [comment]
@andrewshrout Yes, multiple problems here that I fix in content.

- There is no `req.body` for request with method `GET`
- `fetch` requires absolute, not relative, path

**Comment by andrewshrout** [comment]
Awesome. Thanks.
