### ISSUE TITLE
Ch 4 - Jest Testing import issue in sum example

### ISSUE THREAD

**Issue by andrewshrout** [async-labs/saas#121]
Code for "Sum test"
`import { sum } from '../../../server/utils/sum';`

leads to a failure to run the test with 

`error TS2307: Cannot find module '../../../server/utils/sum'.`

**Suggested Fix**
`import { sum } from './sum';`

replicates the results that the chapter says you should get (success).

There are also similar issues in the slug testing, where the example path is off from what a user's path would be.

```
import '../../../server/env';
import User from '../../../server/models/User';
import { generateSlug } from '../../../server/utils/slugify';

```

whereas if you follow the book
```

import '../env';
import User from '../models/User';
import { generateSlug } from '../utils/slugify';
```

Everything is much closer, and doesn't require such a deep directory dive.

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #121</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/121.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by tima101** [comment]
@andrewshrout I checked and file destinations seem to be correct. Changing to `./sum` throws error as it should:

![Screenshot from 2020-09-14 16-10-15](https://user-images.githubusercontent.com/10218864/93147022-32c48c80-f6a5-11ea-9354-9bf8c82337a3.png)
