### ISSUE TITLE
Ch 4 Your Settings -> mozilla url explaining destructuring inside code block prevents compiling

### ISSUE THREAD

**Issue by andrewshrout** [async-labs/saas#122]
**Expected Behavior**
Copy paste the code -> compile.

**Actual Behavior**
```
</Layout>
    );https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Object_destructuring
  }
}

export default YourSettings;
```
`SyntaxError: D:\coding projects\saas-book-course\book\4-begin\app\pages\your-settings.tsx: Unexpected token (53:0)`
Url prevents compiling.

**Suggestion?**
Remove the line of code. It's linked in the explanation directly below this code block.

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #122</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/122.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by klyburke** [comment]
Thank you @andrewshrout ! That was indeed a typo. I removed the link.
