### ISSUE TITLE
Property '_id' does not exist on type 'UserDocument'.

### ISSUE THREAD

**Issue by mrhanson3** [async-labs/saas#125]
I keep running into this error on Heroku, so if anyone knows how I can fix it, please let me know. I'm going to be working on it today. 

-----> Build

       Running build (yarn)

       yarn run v1.22.4

       $ yarn build:api && yarn build:app

       $ yarn --cwd ./api build

       $ tsc --project tsconfig.server.json

       server/google-auth.ts(55,21): error TS2339: Property '_id' does not exist on type 'UserDocument'.

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #125</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/125.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by mrhanson3** [comment]
Below the above, there's this
       server/models/Discussion.ts(107,43): error TS2339: Property 'find' does not exist on type 'typeof DiscussionClass'.

       server/models/Discussion.ts(121,17): error TS2339: Property 'create' does not exist on type 'typeof DiscussionClass'.

       server/models/Discussion.ts(137,35): error TS2339: Property 'findById' does not exist on type 'typeof DiscussionClass'.

       server/models/Discussion.ts(151,35): error TS2339: Property 'findOneAndUpdate' does not exist on type 'typeof DiscussionClass'.

       server/models/Discussion.ts(169,35): error TS2339: Property 'findById' does not exist on type 'typeof DiscussionClass'.

       server/models/Discussion.ts(177,16): error TS2339: Property 'deleteOne' does not exist on type 'typeof DiscussionClass'.

**Comment by tima101** [comment]
@mrhanson3 Please share your exact codebase with me. Looks like some type definitions are missing or some packages of `@types/...` are not installed. Do you get the same errors locally when running `tsc --project tsconfig.server.json` inside `api` folder?

**Comment by mrhanson3** [comment]
here it is: https://github.com/mrhanson3/newsaas

I didn't have any issues locally.

**Comment by tima101** [comment]
@mrhanson3 My build logs for `api` project look like:
```
-----> Build
       Running build (yarn)
       yarn run v1.22.4
       $ tsc --project tsconfig.server.json
       Done in 11.10s.
```

Your's:
```
Running build (yarn)
yarn run v1.22.4
$ yarn build:api && yarn build:app
$ yarn --cwd ./api build
$ tsc --project tsconfig.server.json
```

Where did you add this script command `yarn build:api && yarn build:app`? There should not be such command in build stage.

Please make sure you have two Heroku buildpacks and `PROJECT_PATH` env variable (in addition to all other env variables) for `api` project on Heroku dashboard:

![Screenshot from 2020-09-17 12-54-02](https://user-images.githubusercontent.com/10218864/93521472-f8493280-f8e4-11ea-9bd0-c8152618121b.png)

**Comment by tima101** [comment]
@mrhanson3 Did this resolve the issue?
