### ISSUE TITLE
Yarn in base app directory doesn't work

### ISSUE THREAD

**Issue by andrewshrout** [async-labs/saas#127]
**Expected**
Following this from the readme

Running app locally:
Navigate to the app folder, run yarn to add all packages, then run yarn dev and navigate to http://localhost:3000
=> should install packages

**What happens**
```
error app-same-as-10-end-app@1.0.0: The engine "node" is incompatible with this module. Expected version "12.16.1". Got "12.16.3"
error app-same-as-10-end-app@1.0.0: The engine "yarn" is incompatible with this module. Expected version "1.22.4". Got "1.22.5"
error Found incompatible module.
```

This same thing happens in the api folder.

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #127</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/127.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by tima101** [comment]
@andrewshrout You can install particular Node version and switch easy between versions using `nvm`:

https://github.com/nvm-sh/nvm#usage

**Comment by andrewshrout** [comment]
Thanks. Switched over yarn and node.
