### ISSUE TITLE
Ch 9 - StripePromise unexpected Token

### ISSUE THREAD

**Issue by andrewshrout** [async-labs/saas#129]
**Expected Behavior**
yarn dev in Book 9 app -> check out billing page as per tutorial after the API methods and routes and billing page have been set up.

**Observed behavior**
Can't render the page. Other pages render.
```
SyntaxError: D:\coding projects\saas-book-course\book\7-begin\app\pages\billing.tsx: Unexpected token, expected ";" (17:28)

  15 | const dev = process.env.NODE_ENV && process.env.NODE_ENV !== 'production';
  16 | 
> 17 | const stripePromise = await loadStripe(dev ? process.env.STRIPE_TEST_PUBLISHABLEKEY : process.env.STRIPE_LIVE_PUBLISHABLEKEY);
     |                             ^
  18 | 
  19 | type Props = {
  20 |   store: Store;
```

**Context**
NOTE: Am in book 7 because I do not need most of the functions from book 8 in my end-product. Consolidated all the TeamLeader methods / data types / etc under team-member, as my product will not end up using team leaders. All the API point in the right directions (hopefully) but I can't render the page to even start testing due to this issue that wants a semi-colon.

Would appreciate help.
https://github.com/andrewshrout/saas-book-course/tree/master/book/7-begin

**Comment by andrewshrout** [comment]
**Fixed**
@types/stripe installed, and removing "await" allows stripe to be loaded.

**Comment by tima101** [comment]
@andrewshrout I made small fix to content. Thanks.
