### ISSUE TITLE
Any plans of fixing the dependency issue with the event-stream package and hack?

### ISSUE THREAD

**Issue by willmatos** [async-labs/saas#13]
![screen shot 2019-01-24 at 6 12 50 pm](https://user-images.githubusercontent.com/847623/51714609-cf837380-2003-11e9-8fe9-3e36db7e8209.png)

https://github.com/yarnpkg/yarn/issues/6725

<details>
      <summary>Click to see <b>Hill for issue #13</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/13.png" alt="Single issue hill" class="s3-image"/></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image"/></div></details>
      
created by [Async](https://async-await.com/)

**Comment by tima101** [comment]
@willmatos Have you tried solutions in #11?

**Comment by willmatos** [comment]
Thanks for the quick response, yeah I followed it down and updated nodemon. Is there a chance you could send me an example of the .env file? Your build looks great and I am trying to get her up and running for the first time.

**Comment by tima101** [comment]
@willmatos `.env` file: https://github.com/async-labs/saas#running-api-locally

As for your original question, try removing `yarn.lock` and `node_modules`. Then run `yarn`.
Please let me know if this issue is resolved.

**Comment by willmatos** [comment]
@tima101 Thanks for the help! I was able to get the api and front-end app up and running. I am running into issues with getting S3 all set up but I think that mainly has to do with permissions/type issues in how my S3 buckets are setup. Anyways while troubleshooting that I ran into issues with how to get the API to work in debug mode with node inspect. Do you guys use node inspect to debug the API? And if so how do you get that running? Creating a debug command for yarn: `nodemon --inpsect server/app.ts` seems to hang up the API.

**Comment by tima101** [comment]
@willmatos For S3 bucket setup, check up CORS setup instruction for bucket in our README file: https://github.com/async-labs/saas/blob/master/README.md

I don't know much about `nodemon --inspect`. Sorry.

Please create a separate issue in the future if topic has changed.
