### ISSUE TITLE
Installation unfortunately needs node "12.16.1" and yarn "1.22.4" (no bug)

### ISSUE THREAD

**Issue by deniercounter** [async-labs/saas#131]
LOG:
npm i

> saas-boilerplate@2.0.0 postinstall /home/deniercounter/Github/saas
> yarn --cwd ./api install && yarn --cwd ./app install

yarn install v1.22.5
[1/5] Validating package.json...
error api-same-as-10-end-api@1.0.0: The engine "node" is incompatible with this module. Expected version "12.16.1". Got "13.9.0"
error api-same-as-10-end-api@1.0.0: The engine "yarn" is incompatible with this module. Expected version "1.22.4". Got "1.22.5"
error Found incompatible module.

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #131</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/131.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by tima101** [comment]
@deniercounter Check this issue https://github.com/async-labs/saas/issues/127

**Comment by deniercounter** [comment]
Thanks for the hint. I use nvm, but I don't think I can run different node version in different terminals on the same machine. But maybe with a different user?

But this is not an issue for here.

**Comment by tima101** [comment]
@deniercounter You can either install required versions of Node and Yarn. Or you can deviate from this project and specify your own versions in your own `package.json` file.

**Comment by deniercounter** [comment]
@tima101 Thank you! I only had a look at the root package.json.

**Comment by mrhanson3** [comment]
Hey @deniercounter, I use this to run 12.16.1: https://stackoverflow.com/questions/7718313/how-to-change-to-an-older-version-of-node-js
