### ISSUE TITLE
Remove requirement to assign team member to create Discussion

### ISSUE THREAD

**Issue by klyburke** [async-labs/saas#132]
@tima101 In the SaaS demo app, a new user (Team Leader) is unable to create a Discussion before adding additional Team Members. Discussions currently require that someone, besides the creator of the Discussion, is assigned to that Discussion.

Here is what happens when a Team Leader tries to create a Discussion without assigning anyone:
![Screen Shot 2020-10-04 at 6 25 03 PM](https://user-images.githubusercontent.com/26158226/95032448-73de0a00-066f-11eb-9783-a9fade05ff57.png)

I suggest we remove this requirement. That way, a Team Leader can create a Discussion on their own, without any other Team Members.

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #132</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/132.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by tima101** [comment]
@klyburke Pushed https://github.com/async-labs/saas/commit/1696e55402cf8f91fde87803a880cd8f1f7ce8a0 and clarified in the book
