### ISSUE TITLE
CORS issue for uploading image to Post in demo app

### ISSUE THREAD

**Issue by klyburke** [async-labs/saas#135]
@tima101  Noting to ourselves that in the current demo app, a user is unable to add an image to a Post due to a CORS problem.

`Access to fetch at 'https://saas-api.builderbook.org/api/v1/team-member/aws/get-signed-request-for-upload-to-s3' from origin 'https://saas-app.builderbook.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

![Screen Shot 2020-11-30 at 4 46 47 AM](https://user-images.githubusercontent.com/26158226/100612199-6dfb5280-32c7-11eb-9f5a-f162c6601c26.png)

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #135</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/135.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by tima101** [comment]
@klyburke Image upload works on `YourSettings` page, meaning it is not S3 problem, must be problem in Post-related code. I will report here when I find out.

**Comment by tima101** [comment]
@klyburke Pushed fix 
https://github.com/async-labs/saas/commit/83fa735034672ddabff46875c358d7c06106ac5c
https://github.com/async-labs/saas/commit/f4c89cb6f0b676b79f659dd19142e0fde1b78ac2

One of env var was not available on the browser.
Let's keep it open until I make fix in the book's content.

**Comment by tima101** [comment]
@klyburke Solved.

**Comment by klyburke** [comment]
I confirm that image upload in a Post is working now. Thanks!
