### ISSUE TITLE
Links are broken in the introduction

### ISSUE THREAD

**Issue by Khobalt** [async-labs/saas#153]
You're missing the extra branch portion of the urls for the [Introduction](https://builderbook.org/books/saas-boilerplate/introduction-project-structure#what-will-you-learn-):

![image](https://user-images.githubusercontent.com/848683/108603859-483a9280-7378-11eb-951c-519ee0b60dd9.png)

**Comment by klyburke** [comment]
@Khobalt Thank you for catching and reporting! This is now fixed.
