### ISSUE TITLE
Login with email pops up 'failed to fetch' modal at the live demo

### ISSUE THREAD

**Issue by Khobalt** [async-labs/saas#154]
![image](https://user-images.githubusercontent.com/848683/108603958-f5ada600-7378-11eb-9b24-9b229a7f9514.png)

From the [live demo](https://saas-app.async-await.com/login).

**Comment by Khobalt** [comment]
![image](https://user-images.githubusercontent.com/848683/108604029-60f77800-7379-11eb-8ad0-334b29e72f2c.png)

**Comment by tima101** [comment]
@Khobalt Thanks for reporting! Here is the answer: https://github.com/async-labs/saas/issues/155#issuecomment-783599262
