### ISSUE TITLE
Login with Google redirects to 'This site can't be reached'

### ISSUE THREAD

**Issue by sikemausa** [async-labs/saas#155]
After clicking the login with google button, I'm redirected to 'This site can't be reached'. Was considering purchasing the book, but wanted to check the app out first.

<img width="694" alt="Screen Shot 2021-02-22 at 6 35 48 AM" src="https://user-images.githubusercontent.com/19242172/108715926-b9915700-74d8-11eb-8024-0868109e30ce.png">

**Comment by tima101** [comment]
@sikemausa Thanks for reporting. I updated values for env variables on our Heroku dashboard but this update did not take effect. Locally, both authentication methods work as expected. I redeployed demo projects and I see that update took effect. 

In addition to the above, this fix:
https://github.com/async-labs/saas/commit/2f144a24c45c943780a8b6bba1ba4e668fb30746
