### ISSUE TITLE
Integration of Stripe Tax

### ISSUE THREAD

**Issue by kevinpeters-stripe** [async-labs/saas#167]
Hey,

Kevin from Stripe here. I was wondering if you want to extend your book with Stripe Tax. On hackernews someone requested to talk about taxes as well: https://news.ycombinator.com/item?id=24173577

> You guys use stripe for payments in the book but what about taxes? I feel a good addition to your book would be to mention Paddle as they operate as a merchant of record so taxes are accounted for.

We recently released [Stripe Tax](https://stripe.com/en-gb-de/tax) which should account for most of struggles customer's had with tax solutions.

If you have any question about Stripe Tax, feel free to ask here :)

**Comment by klyburke** [comment]
Hi @kevinpeters-stripe. Thanks for sharing! We will look into this in our November update: https://github.com/async-labs/saas/issues/163

**Comment by tima101** [comment]
@kevinpeters-stripe It looks like SaaS software is not taxable in many places. Also Stripe requires activating tax feature and Stripe takes 0.5% after that. This makes little sense for SaaS boilerplate to add tax integration.
