### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by athahersirnaik** [async-labs/saas#170]
1. Shall we move the env variables to `.env.example` instead of Readme
2. I'm working on adding additional email driver like `smtp` and `log` that can be controlled by `.env`
3. Instead of checking dev environment eveytime, we can use [config](https://www.npmjs.com/package/config). Let me know if I should create PR for this?

**Comment by athahersirnaik** [comment]
Instead of checking dev environment eveytime, we can use [config](https://www.npmjs.com/package/config). Let me know if I should create PR for this?

**Comment by tima101** [comment]
@athahersirnaik Hi, thanks for suggestions. We plan to keep AWS SES infrastructure for emails, no plans to add other options. And `config` seems to add more configuration than necessary. You can do your own email implementation on your fork. As for 1), seems like a good idea.

**Comment by athahersirnaik** [comment]
Ok, I'm adding config in my fork, you can check it if you want the same, then I'll create a PR
