### ISSUE TITLE
Can't modify the session (Chapter 5)

### ISSUE THREAD

**Issue by rohidas-gowda** [async-labs/saas#177]
In the chapter 5,  In "save session to database" section
``` 
req.session.foo = 'bar';
 ``` 
is giving following error

``` 
Property 'foo' does not exist on type 'Session & Partial<SessionData>' 
``` 
So I am not able to modify the sessions.
The error path: 

```
book/5-begin/api/server/api/public.ts
```

**Comment by rohidas-gowda** [comment]
Here is the repo I get the error:
https://github.com/rohidas-gowda/saas/blob/master/book/1-begin/api/server/api/public.ts
At line 10

**Comment by klyburke** [comment]
@rohidas-gowda Thanks for reporting and sharing your code base.

I tested your code and see the problem. As a quick solution to get the code running, you can write `//@ts-ignore` above the line `req.session.foo = 'bar';`.

That worked for me, but I will look into a better solution, if it makes sense for this example in the book.

**Comment by rohidas-gowda** [comment]
Thanks @klyburke
