### ISSUE TITLE
Send email for a new Post

### ISSUE THREAD

**Issue by tima101** [async-labs/saas#18]
- When a new Post is created, send email to all members of Discussion.
- Host code on AWS Lambda
- Send email with AWS SES

This issue is part of #14

---

Steps:
-  At `app`: 
  - (done) modify create/edit forms for Discussion,
  - (done) notificationType on store and server for Discussion,
  - (done) API method (`sendEmailForNewPost`) that sends request from `app` to Lambda via API Gateway
  - (done) create env var for `LAMBDA_API_ENDPOINT` and add it to `app`
  - (done) create email template for new Post at `api`
  - (done) email is sent when new Discussion is created, make sure that email is sent for new Post inside existing Discussion
- At `lambda`: Lambda function that sends email to all members of Discussion except the user who created a new Post
  - (done) deployed and tested API Gateway (POST method)
  - (done) pass and print `discussionName`, `authorName`, `postContent`, `userIds` to `sendEmailNotification` function
  - (done) send email to each user from `userIds`

---

<details>
      <summary>Click to see <b>Hill for issue #18</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/18.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image"width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by tima101** [comment]
@delgermurun Would you please test out this feature when you have time? Any feedback is welcome.

**Comment by delgermurun** [comment]
@delgermurun Okay.
