### ISSUE TITLE
NProgress code does not work as shown

### ISSUE THREAD

**Issue by michaelklem** [async-labs/saas#180]
https://builderbook.org/books/saas-boilerplate/material-ui-client-side-and-server-side-rendered-pages-dark-theme-cssbaseline-shared-layout-adding-styles-shared-components-menuwithlinks-notifier-confirmer-nprogress-mobile-browser#nprogress

I ended up using this npm module "@tanem/react-nprogress" and  I needed to add more components I copied from an react-nprogress example to get working.

I can provide files as needed or give you access to my code.

**Comment by klyburke** [comment]
@michaelklem Thanks for reporting.

Can you please explain in more detail what you mean by "does not work as shown"?

I ran `2-end` and clicked the `Test Confirmer and Notifier` button. I then see the progress bar run at the top of the page.

Yes, if you'd like to create a public repo with the exact code you are running, I can look at that.

**Comment by michaelklem** [comment]
You are correct. Your code works.
The use of NProgress.done() prevented me from seeing the progress bar
enough.

**Comment by klyburke** [comment]
@michaelklem Thanks for following up!
