### ISSUE TITLE
tsconfig.json requires "tsBuildInfoFile" setting

### ISSUE THREAD

**Issue by joelhenryclark123** [async-labs/saas#185]
Sorry if this is poorly written... my first ever issue submission

Found this bug in chapter 1, but it looks like it exists in all chapters. I get an error when running "yarn build" that says the --incremental flag must be accompanied by --tsBuildInfoFile. I solved this by adding "tsBuildInfoFile": ".tsBuildInfo" right below "incremental":true in tsconfig.json

tsconfig.json:
`{
  "compileOnSave": false,
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "jsx": "preserve",
    "allowJs": true,
    "alwaysStrict": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "removeComments": true,
    "preserveConstEnums": true,
    "sourceMap": true,
    "skipLibCheck": true,
    "baseUrl": ".",
    "typeRoots": [
      "./node_modules/@types"
    ],
    "lib": [
      "dom",
      "es2017"
    ],
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "incremental": true,
    "tsBuildInfoFile": ".tsbuildinfo"
  },
  "include": [
    "next-env.d.ts",
    "./**/*.tsx",
    "./**/*.ts"
  ],
  "exclude": [
    "dist",
    "production-server",
    ".next",
    "out",
    "next.config.js",
    "node_modules"
  ]
}`

package.json:
`{
  "name": "1-end-app",
  "version": "1",
  "license": "MIT",
  "scripts": {
    "dev": "next",
    "build": "next build && tsc --project tsconfig.server.json",
    "lint": "eslint . --ext .ts,.tsx"
  },
  "dependencies": {
    "dotenv": "^8.2.0",
    "next": "^9.1.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "typescript": "^4.7.3"
  },
  "devDependencies": {
    "@types/node": "^12.12.2",
    "@types/react": "^18.0.14",
    "@types/react-dom": "^18.0.5",
    "@typescript-eslint/eslint-plugin": "^4.2.0",
    "@typescript-eslint/parser": "^4.2.0",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^7.1.0",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-react": "^7.21.5",
    "prettier": "^2.2.1"
  }
}`

**Comment by klyburke** [comment]
@joelhenryclark123 Thanks for reporting and providing a solution. I'll check this once I get a chance and report back.

**Comment by klyburke** [comment]
Thanks again @joelhenryclark123 . I confirm this issue and that your solution works. I'll update the code and book text.
