### ISSUE TITLE
[chapter 6] styleLoginButton is not defined

### ISSUE THREAD

**Issue by michaelklem** [async-labs/saas#186]
Using 6-begin code, the css style styleLoginButton is not defined in the code. The docs show this:

`<Button variant="contained" style={styleLoginButton} href={url}> `

But this works:

`<Button variant="contained" color="primary" href={url}>`

**Comment by klyburke** [comment]
@michaelklem Thank you for reporting and good catch. This is a typo in the book text.

In the book text, we wrote `<Button variant="contained" style={styleLoginButton} href={url}>` in the LoginButton component.

However, in the actual code, we have `<Button variant="contained" color="secondary" href={url}>` in the LoginButton component.

You could also use `color="primary"`. The style you prefer is up to you.

I will fix the typo in the book text.

Sorry for the delay in responding to this issue, as I was traveling.
