### ISSUE TITLE
One-time payments for "credits"

### ISSUE THREAD

**Issue by sgbaird** [async-labs/saas#187]
Curious if you have any suggestions for having an option for purchasing "credits" via one-time purchases, similar to [DALLE-2](https://openai.com/dall-e-2/)'s pricing model.

https://github.com/saasforge/open-source-saas-boilerpate/issues/39

**Comment by klyburke** [comment]
Hi @sgbaird . Not familiar with how to set up buying "credits", but our [builderbook repo](https://github.com/async-labs/builderbook) has Stripe implemented for single payments - in our case one-time payment for access to a digital book. Hope that helps. You may want to ask Stripe about "credits".
