### ISSUE TITLE
Chapter 9: AWS Lambda Serverless Deployment issue (over size)

### ISSUE THREAD

**Issue by Dolvido** [async-labs/saas#192]
Hi!

Worked along with the book up through chapter 9 when attempting to deploy the project in the recommended way (api symlink, copying api project package.json and associated modules) and ran into the issue when trying to run the 'serverless deploy' command along with the book's instructions.
output from command: 

Environment: linux, node 12.22.0, framework 3.25.1, plugin 6.2.2, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
CREATE_FAILED: SendEmailForNewPostLambdaFunction (AWS::Lambda::Function)
Resource handler returned message: "Unzipped size must be smaller than 262144000 bytes (Service: Lambda, Status Code: 400, Request ID:<my req ID>)" (RequestToken: <my req token>, HandlerErrorCode: InvalidRequest)

Just curious how you would work around the size limit for the lambda project when mirroring the packages from the api project/using the api symlink. Thank you for your time!

**Comment by tima101** [comment]
250 MB seems too large SendEmailForNewPostLambdaFunction

I plan upgrade serverless and review serverless instructions in the book later this month. We will send out email after upgrade.
