### ISSUE TITLE
Chapter 3 End - Server Error 426

### ISSUE THREAD

**Issue by shaunmichaelwalker** [async-labs/saas#194]
Hello - just refactored from 1- to 2-server architecture as described at the end of Ch. 3 and am getting a 426 error in my app project (frontend): 

<img width="739" alt="image" src="https://user-images.githubusercontent.com/8185777/215345628-d95fe4a9-4108-49da-9f09-036bba462cbe.png">

The console messages are printing from here, in **sendRequestAndGetResponse.ts:**

<img width="568" alt="image" src="https://user-images.githubusercontent.com/8185777/215345668-c3b14153-dabe-4e0c-a6c4-9df61295e420.png">

Based on some research, I think this is because the api server will not accept HTTP1.*, which is what it looks the app server is using (printed these opts from **sendRequestAndGetResponse.ts**): 

<img width="265" alt="image" src="https://user-images.githubusercontent.com/8185777/215345842-d1f994ab-4674-44b1-9042-7533c531667c.png">

I tried upgrading isomorphic-unfetch to 4.0.2 (current version), deleted yarn.lock and node_modules, and ran **yarn**. That did nothing. I'm also not having any issue when I access the endpoint directly from the browser:

<img width="771" alt="image" src="https://user-images.githubusercontent.com/8185777/215345942-2a59a38e-f189-4f00-b945-229d5996c06f.png">

Assuming the **Upgrade Required** status text does in fact mean I need to upgrade to HTTP2, how can I do this?

**Comment by klyburke** [comment]
@shaunmichaelwalker Thanks for reporting.

Do you see this error when you run our exact `3-end` code?

**Comment by tima101** [comment]
@shaunmichaelwalker I haven't reproduced you issue. Could you try changing port `3000` to some other value? Say, `3030` or any other allowed and available value on your machine.

Please keep module versions the same as described in the book. Upgrading packages may add breaking changes.
