### ISSUE TITLE
Chapter 3 End - Next/Express server not starting

### ISSUE THREAD

**Issue by sivaram-psg** [async-labs/saas#195]
When I run '_yarn dev_' in chapter3-end/app folder, express/nextjs server not starting. The below are console logs

_(base) sree@sree-HP-Laptop-15-da0xxx:~/code/bank_login_book/saas/book/3-end/app$ yarn dev
yarn run v1.22.19
$ nodemon server/server.ts
[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): server/**/*
[nodemon] watching extensions: ts
[nodemon] starting `ts-node --project tsconfig.server.json server/server.ts`
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
event - compiled successfully
> Ready on undefined_

**Comment by sivaram-psg** [comment]
I observe NEXT_PUBLIC_PORT_APP and NEXT_PUBLIC_URL_APP have the value of 'undefined' . After setting this values while starting the server, there are no issues _'NEXT_PUBLIC_PORT_APP=3000 NEXT_PUBLIC_URL_APP=http://localhost nodemon server/server.ts'_

**Comment by klyburke** [comment]
@sivaram-psg Thanks for reporting. Did you solve the problem by adding values to your environmental variables, `NEXT_PUBLIC_PORT_APP` and `NEXT_PUBLIC_PORT_API`?

I just tested the `3-end` code and was able to successfully run the `app` and `api` projects. For the above environmental variables, I am using:

```
NEXT_PUBLIC_PORT_APP=3000
NEXT_PUBLIC_PORT_API=8000
```
