### ISSUE TITLE
Unable to run the app, Internal Server Error

### ISSUE THREAD

**Issue by dentalht** [async-labs/saas#21]
I'm following the instructions to get it running locally
I setup my .env file as instructed. when i run api & app, and navigate to http://localhost:3000
i get Internal Server Error page and console throws this error

> TypeError: Cannot read property 'theme' of undefined                                                                                                                                                                        at MyDocument.render (E:\Development\Gitlabs\SaaS\app\.next\server\static\development\pages\_document.js:2194:48)                                                                                                       at processChild (E:\Development\Gitlabs\SaaS\app\node_modules\react-dom\cjs\react-dom-server.node.development.js:2942:18)                                                                                               at resolve (E:\Development\Gitlabs\SaaS\app\node_modules\react-dom\cjs\react-dom-server.node.development.js:2795:5)                                                                                                     at ReactDOMServerRenderer.render (E:\Development\Gitlabs\SaaS\app\node_modules\react-dom\cjs\react-dom-server.node.development.js:3185:22)                                                                              at ReactDOMServerRenderer.read (E:\Development\Gitlabs\SaaS\app\node_modules\react-dom\cjs\react-dom-server.node.development.js:3144:29)                                                                                at Object.renderToStaticMarkup (E:\Development\Gitlabs\SaaS\app\node_modules\react-dom\cjs\react-dom-server.node.development.js:3644:27)                                                                                at renderDocument (E:\Development\Gitlabs\SaaS\app\node_modules\next-server\dist\server\render.js:51:18)                                                                                                                at Object.renderToHTML (E:\Development\Gitlabs\SaaS\app\node_modules\next-server\dist\server\render.js:114:12)                                                                                                          at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by tima101** [comment]
@dentalht I was traveling and will look into this issue later today (late evening, PST).

**Comment by tima101** [comment]
@dentalht Thanks for reporting! I confirm problem.

Problem occurs due to the fact that `store.currentUser` and `store.currentUser.darkTheme` are null for logged out user.

Commit:

**Comment by dentalht** [comment]
Yep, that seem to have done the trick. I'm able to launch the app now. Thank you.
