### ISSUE TITLE
Error when updating team name or logo. NProgress not defined

### ISSUE THREAD

**Issue by pbaveja** [async-labs/saas#24]
In the following:

> app/pages/team-settings.tsx

NProgress has not being imported and any attempt to update throws an `NProgress is not defined` error
![Screenshot from 2019-04-30 16-39-35](https://user-images.githubusercontent.com/22319179/56958046-b3ddbb00-6b66-11e9-8532-75fe74e0bd50.png)

Solution: Just a simple `import NProgress from 'nprogress';` on this page

<br/><hr/><details>
      <summary>Click to see <b>Hill for issue #24</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/24.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by tima101** [comment]
@pbaveja Thanks! Would you like to create a pull request with fix?

**Comment by pbaveja** [comment]
Sure! I'll just do that :+1:
