### ISSUE TITLE
Multitenancy

### ISSUE THREAD

**Issue by Amurmurmur** [async-labs/saas#26]
Any plans to support a multi-tenancy ? 

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #26</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/26.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by tima101** [comment]
@Amurmurmur Please elaborate a bit more. Thanks.

**Comment by Amurmurmur** [comment]
@tima101 I think this article will explain it better than me :)
http://books.agiliq.com/projects/django-multi-tenant/en/latest/introduction.html#the-structure-of-this-book

**Comment by tima101** [comment]
@Amurmurmur I've checked the link. Do you mean connecting one Node app (say `api` app) to multiple databases?

**Comment by thealbertyang** [comment]
Do you guys have support for multiple databases connecting to one Node app?

**Comment by tima101** [comment]
@Amurmurmur @thealbertyang `api` app connects to one database and `app` gets data from `api` via "internal" APIs.

**Comment by jaylensoeur** [comment]
@Amurmurmur from your link you can use:
- Shared database with shared schema
- Shared database with isolated schema

**Comment by kunalahirrao** [comment]
Does it create separate database for each user ???

**Comment by tima101** [comment]
@kunalahirrao https://github.com/async-labs/saas/issues/81#issuecomment-643565552
