### ISSUE TITLE
yarn test failing

### ISSUE THREAD

**Issue by pnmcosta** [async-labs/saas#27]
Hi There,

I'm new to React + TypeScript, thank you so much for this boilerplate, it will undoubtly allow me to learn a lot! :)

I did manage to get it all setup and building, however I was getting a fail on `yarn test`, on closer inspection the only test was a `js`, I migrated the code to TS and also made sure it ran.

Whilst doing that I came across a couple more issues (mostly with my IDE - vscode) so I also added a specific tsconfig on the test directory.

Anyway, all is in this fork https://github.com/pnmcosta/saas-boilerplate, and I'll happily PR it if you wish to. Please do note that `mockingoose`, `ts-jest` and `@types/jest` have been added to the api's devDeps.

Cheers,
P.

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #27</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/27.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by tima101** [comment]
@pnmcosta Thanks for question. Do you describe `yarn test` in `app` or `api`?

**Comment by pnmcosta** [comment]
@tima101 it's the `api`'s I'm referring above.  I migrated the test to ts and added the config file. But later on another branch on my fork I opted to modify the default config to include tests and have a separate config for the build (like app does).

**Comment by tima101** [comment]
@pnmcosta Thank you for converting test to TS. Please create PR, I will merge it.

**Comment by pnmcosta** [comment]
Done, see https://github.com/async-labs/saas/pull/29
