### ISSUE TITLE
docker support?

### ISSUE THREAD

**Issue by pnmcosta** [async-labs/saas#28]
Hi,

Not sure what your take on [docker](https://docs.docker.com/install/) as a support tool for dev/testing and even staging/production is. 

I am familiar with it from other projects, and combining it with your boilerplate made sense to me, you can find my work-in-progress branch [here](https://github.com/pnmcosta/saas-boilerplate/tree/docker-support) feel free to check/review/comment and if you want I can PR it.

Docs here: https://github.com/pnmcosta/saas-boilerplate/wiki/Changes-on-docker-support-branch

Cheers,
P.

**Comment by pnmcosta** [comment]
Done good progress on it for now, will let it rest for a bit. 

Did come across an issue where I'm asking for some help here: https://stackoverflow.com/questions/56459243/docker-compose-build-time-args-from-file

If anyone could chip in, i'd be most grateful.

Cheers,
P.

**Comment by pnmcosta** [comment]
I think I found a good compromise to the issue above, I've created the following PR so you can better analyse what has been changed.

IMO, it's now a proposal, not WIP anymore, if you'd like to merge :)

**Comment by tima101** [comment]
@tima101 Thanks. I love it. I just merged PR that adds docker to https://github.com/builderbook/builderbook

**Comment by pnmcosta** [comment]
Awesome :) Do you want me to creat a single PR with this and #27? or keep them separate?

**Comment by pnmcosta** [comment]
Sorry, went ahead and did separately, new one here: https://github.com/async-labs/saas/pull/30 but do note it includes all the changes on #29 as well.
