### ISSUE TITLE
next.js v9

### ISSUE THREAD

**Issue by dubvfan87** [async-labs/saas#31]
Are there any plans to upgrade to next.js v9? It has some cool new features like support for api routes. I was thinking this could get rid of the need to run 2 separate apps.

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #31</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/31.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by tima101** [comment]
@dubvfan87 Eventually, yes. No particular deadline. 

Having `app` and `api` separated is not simply a matter of organization.
When `app` and `api` are separated, page rendering in `app` does not block request processing in `api`.
And vice versa, request processing in `api` does not block page rendering in `app`.

Separation of `app` and `api` is done to create more scalable, production-ready app.

`api` routes that you mentioned in v9, from my quick glance, is opinionated feature that has opinion on where you should keep code for your app's routes. This new feature prescribes storing code for routes in `pages/api`, we store routes in `lib/api`. Not a big deal.

**Comment by tima101** [comment]
@dubvfan87 Next was recently upgraded to v9 in all web apps of `saas` repo.

Thanks to @delgermurun

**Comment by dubvfan87** [comment]
Nice thanks for the heads up, and thanks to @delgermurun !
