### ISSUE TITLE
Information About Purchase to Builder Book/Saas

### ISSUE THREAD

**Issue by offwork** [async-labs/saas#32]
First of all, congratulations, I have a question; How do I know if your payment method is valid at my location? Because I've had trouble with that before. I'm waiting for your answer.

Thanks in advance.

I live in Istanbul/Turkey.

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #32</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/32.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by klyburke** [comment]
@offwork thank you for the congrats.

We have had readers purchase our book from Turkey. The location should not be an issue. Stripe supports 135+ currencies, which are listed here: https://stripe.com/docs/currencies

If you do have trouble with purchasing, you can email us: team@builderbook.org.

**Comment by offwork** [comment]
thanks for your fast reply 👍
