### ISSUE TITLE
Cannot find SocketIOClient on deployment to Heroku

### ISSUE THREAD

**Issue by Moai-** [async-labs/saas#34]
Upon deploying to Heroku, my build failed with the following message:  

```
remote:        lib/store/index.ts(31,18): error TS2503: Cannot find namespace 'SocketIOClient'.
remote:        lib/store/index.ts(40,14): error TS2503: Cannot find namespace 'SocketIOClient'.
remote:        error Command failed with exit code 2.
remote:        info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
remote:        error Command failed with exit code 2.
remote:        info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
and Heroku rejected the build. I was able to solve this problem by manually moving my `node_modules/@types` folder to a local folder (in my case, `app/lib`) and redirecting `typeRoots` inside tsconfig towards the folder I moved it to, instead of node_modules. 

This error should be reproducible by just taking a fresh copy of this repo, and following instructions to upload it to Heroku. I'm not exactly sure what the underlying problem is, as the app builds fine on my machine. Error occurs only upon deployment to Heroku.

**Comment by tima101** [comment]
@Moai- I just tested by deploying `/app` project from this repo to Heroku and deployment worked as expected. Deployment is mapped to: https://saas-app.async-await.com/

I am not sure what modifications you made to `/app` but there is no need to move `@types` folder.
Make sure that you did not modify config files at the root of the `/app` folder.

**Comment by Moai-** [comment]
Cloned into a fresh directory & deployed. Everything works as expected. Not sure why it didn't last time, but it seems the problem is on my end. Closing.
