### ISSUE TITLE
Create more complete guide for suggested deployment method

### ISSUE THREAD

**Issue by Moai-** [async-labs/saas#35]
First I'd like to say that this platform is great. It is exactly what I was looking for, a starting point that does not rely on too many frameworks within an ecosystem I am familiar with (React). Now that I have all parts of it set up, I can't wait to start hacking at it and creating something new and cool out of it.  

That said, it did take me a good four days of fierce googling and debugging to get everything deployed. I'm coming from an Electron.js background, having done small-scale desktop and mobile development for the last while, and everything from Mailchimp to SES to S3 was new to me. I feel these things aren't obvious, and would love a doc to talk about it in closer detail, so others could hit the ground running faster. I realize there's a bit where you guys talk about how you publish one of the books, but it doesn't say anything about the third party services.

My method kind-of sort-of works -- haven't tested out Stripe API yet and haven't bugged SES to let me send unverified emails, but everything aside from that works. I did end up modifying a couple of things (in particular related to CORS issues, where my `.herokuapp.com` API address was breaking my own `api.example.com` cookies, even after following the custom domain registration). I don't know how right everything is. In particular, I have no idea what AWS Elastic Beanstalk is, which sounds like a deployment process that is different from what I did. That said, if the Elastic Beanstalk tutorial is still a ways out, I can put together a PR that'll get people from A to B after having just done that.

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #35</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/35.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by tima101** [comment]
@Moai- Are you suggesting some improvements to Heroku deployment guide?
