### ISSUE TITLE
Can't start API

### ISSUE THREAD

**Issue by cMack87** [async-labs/saas#4]
I've configured .env as instructed, hitting an error when trying to start the API locally:

(node:22825) UnhandledPromiseRejectionWarning: TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:202:9)
    at new Buffer (buffer.js:158:17)

**Comment by cMack87** [comment]
Looks like this is related to Mailchimp auth (mailchimp.ts:L22)

I assumed MAILCHIMP_REGION is the last few characters of MAILCHIMP_API_KEY (in my case 'us19') but I couldn't find any clear documentation.

Aside:  Could Mailchimp be moved to the 'optional' section for setup?

**Comment by tima101** [comment]
@cMack87 You I assumed correct. Mine is `us17`.

You can comment out block of code inside `api/server/models/User.ts`:
```
    try {
      await subscribe({
        email,
        listName: 'signups',
      });
    } catch (error) {
      logger.error('Mailchimp error:', error);
    }
```

Also comment out import line: `import { subscribe } from '../mailchimp';`

**Comment by cMack87** [comment]
I guess Mailchimp is not the problem.

I'm not sure what to enter for SESSION_NAME and SESSION_SECRET?  I have double checked all of my other .env variables and they seem fine.

**Comment by cMack87** [comment]
Are you able to run the API and Authenticate with G+ locally?  According to the Google, that shouldn't be possible:

'To protect you and your users, Google only allows applications that authenticate using OAuth to use Authorized Domains. Your applications' links must be hosted on Authorized Domains.'

**Comment by tima101** [comment]
@cMack87 

> I'm not sure what to enter for SESSION_NAME and SESSION_SECRET? 
Take a look at README file, it has 2 links to answer your question:
- https://github.com/expressjs/session#name
- https://github.com/expressjs/session#express

> Are you able to run the API and Authenticate with G+ locally? According to the Google, that shouldn't be possible
Yes, testing on local is possible. When you create your web app on Google Cloud, you provide URLs of authorized domains:
![screenshot from 2018-10-02 19-35-51](https://user-images.githubusercontent.com/10218864/46387244-a321a100-c67a-11e8-935f-3d3d42c35bb9.png)

**Comment by cMack87** [comment]
Turned out to be an issue with my MONGO_URL configuration.  Sorry for the confusion!

**Comment by tima101** [comment]
@cMack87 I am glad you figured it out.
