### ISSUE TITLE
Create more complete guide for acquiring .env values

### ISSUE THREAD

**Issue by BrettKoenig** [async-labs/saas#42]
I'm not sure if this will be included when the book is finished, but getting the config values for the .env file requires getting values from a lot of different sources and different configurations. It would be helpful if there was better documentation around that process.

I would love to submit a PR for it, but I haven't been able to figure all of it out myself yet.

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #42</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/42.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by tima101** [comment]
@BrettKoenig Sorry for delay. Do you mean acquiring API keys and secrets? We plan to explain it in the same we explained for https://github.com/builderbook/builderbook

**Comment by BrettKoenig** [comment]
No I'm sorry for the delay! Is that more extensive than what exists in the [readme ](https://github.com/async-labs/saas/blob/master/README.md) as is today?
