### ISSUE TITLE
Retrieve Card function fails

### ISSUE THREAD

**Issue by jamesoshea** [async-labs/saas#43]
I currently can't set up a card/subscription on the billing page.

I think this is because the types provided by `@types/stripe` are inaccurate -- there is no retrieveCard function on the customers object.

If I change the `retrieveCard` function in `api/server/stripe.ts` to the following, it seems to work (I've just been testing this with a test stripe account):

```
async function retrieveCard({ customerId, cardId }) {
  logger.debug(customerId);
  logger.debug(cardId);
  const cards = await stripeInstance.paymentMethods.list({
    customer: customerId,
    type: 'card',
  });
  return cards.data[0];
}
```

Admittedly, this doesn't fit the coding style at all  😄, and would only support a single payment method per user. It seems as if a new approach is needed to grab the card details.

Thanks for all of the time that has gone into this project, it's amazing.

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #43</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/43.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by tima101** [comment]
@jamesoshea Would you provide exact error message?

I haven't tested current code for some time but try:
- upgrading `@types/stripe` to `6.31.4`
- using following definition:
```
function retrieveCard({ customerId, cardId }) {
  logger.debug(customerId);
  logger.debug(cardId);
  return stripeInstance.customers.retrieveSource(customerId, cardId);
}
```

Would you please test and report here?
Thanks.

**Comment by jamesoshea** [comment]
The error message was this:

```
error: TypeError: stripeInstance.customers.retrieveCard is not a function
    at Object.retrieveCard (/Users/j.oshea/git/avail-saas/api/server/stripe.ts:49:35)
    at Function.<anonymous> (/Users/j.oshea/git/avail-saas/api/server/models/User.ts:239:27)
    at step (/Users/j.oshea/git/avail-saas/api/server/models/User.ts:45:23)
    at Object.next (/Users/j.oshea/git/avail-saas/api/server/models/User.ts:26:53)
    at fulfilled (/Users/j.oshea/git/avail-saas/api/server/models/User.ts:17:58)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```
However, upgrading the type definitions and using your function definition worked perfectly

**Comment by tima101** [comment]
@jamesoshea Thanks. Let's keep open until we make changes.

Would you open PR with necessary changes?

**Comment by jamesoshea** [comment]
For sure, will do!
