### ISSUE TITLE
inclusion of "book" folder in the boilerplate

### ISSUE THREAD

**Issue by GrayStrider** [async-labs/saas#48]
Is "book" folder a copy of https://github.com/builderbook/builderbook/tree/master/book? If so, what is the reason to include it in **boilerplate**? I had to delete it, since Node.js consumed insane amount of RAM and CPU by parsing all 2600 files.

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #48</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/48.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by tima101** [comment]
@GrayStrider Hi, no, this is upcoming second book with 14 chapters. Link you provided is our first book with 8 chapters.

We use this repo to promote upcoming book (the one with 14 chapters).

**Comment by GrayStrider** [comment]
Just so I don't break something accidentally, does `book` directory has any relations to the rest of the boilerplate? Can I safely remove it?
Also, why not have a separate branch for each chapter, what's the reasoning? Node grows to 1.7GB in size while indexing everything.

**Comment by delgermurun** [comment]
@tima101 I think storing book code in different branches is a good idea.

**Comment by klyburke** [comment]
@GrayStrider thanks for bringing this up.

@tima101 @delgermurun I suggest not to move the book code into different branches. I think moving between branches will confuse readers and make the book code harder to find.

Instead, let’s put a note in the README to say that the book folder is not necessary to run the boilerplate and can therefore be deleted.

**Comment by GrayStrider** [comment]
Anyways, issue may be closed as your convinience

**Comment by tima101** [comment]
@delgermurun What are pros and cons?

**Comment by delgermurun** [comment]
@tima101 @klyburke For those who are not familiar with `git` may have difficulty for finding book code.
If we have only one branch for a book code (`book` branch) and telling it on README, I think it is okay.

**Comment by tima101** [comment]
@delgermurun @klyburke Good points. Let's move to different branch.

When we move book code, we need to:
- noticeable memo in README on how to find book code
- update all links in the book's text (builderbook.org)
- update instructions in the book's text (builderbook.org)
- update links inside email templates if any
