### ISSUE TITLE
use lerna and split in multi packages/modules

### ISSUE THREAD

**Issue by sibelius** [async-labs/saas#5]
it would be cool to only include what modules that is needed for a specific saas

**Comment by sibelius** [comment]
each Saas has specific requirements, so only could have social login and another don't

one could want a modules but not another

**Comment by tima101** [comment]
@sibelius I see, interesting. Are you suggesting some sort of boilerplate generator where you select what to include and generate boilerplate with only features you selected?

**Comment by sibelius** [comment]
it could be packages that will be consumed by this boilerplate

**Comment by tima101** [comment]
I guess this would be useful when boilerplate has many options/features. Say multiple signup methods. For now this is not the case. I will keep it in mind for future.
