### ISSUE TITLE
Yarn warnings

### ISSUE THREAD

**Issue by D8ATech** [async-labs/saas#58]
I have just started going through the book.  I am in 1-begin and running yarn for the very first time after creating package.json and I get the following warnings:

```
yarn install v1.19.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning next > @babel/runtime-corejs2 > core-js@2.6.10: core-js@<3.0 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning next > fork-ts-checker-webpack-plugin > chokidar > fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
warning next > styled-jsx > babel-types > babel-runtime > core-js@2.6.10: core-js@<3.0 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
```

while these are just warnings I don't anticipate this causing a problem but would like to see a clean output.

node version: 13.2.0
development environment: OSX Mojave 10.14.6

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #58</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/58.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by tima101** [comment]
@D8ATech You can subscribe to the below issue and get notified when Next.js maintainers make core-js update:
https://github.com/zeit/next.js/issues/8103
