### ISSUE TITLE
Issue with Paswordless login

### ISSUE THREAD

**Issue by mattp95** [async-labs/saas#59]
I have noticed a few issues with paswordless auth, are these to be considered bugs?

User joins via paswordless it says on the user screen that they signed up via google.

If user doesn't have a photo, thier name doesn't display on the team members list.

if a user is invited to join a team, then signs in paswordless with the same email it assumes they are creating a new account. If they then sign in using google they have lost access to that old team and now join that newly created account?

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #59</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/59.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by delgermurun** [comment]
Hi @mattp95,

Thanks for debugging and bringing up critical issues.
I believe fixed all of them. Please test.

Thank you.
