### ISSUE TITLE
Rest API

### ISSUE THREAD

**Issue by mattp95** [async-labs/saas#60]
Hi there,
I am wandering if the rest API is safe to expose publicly, documenting it in OpenAPI format and extending it with application specific code?

Has anybody done this?

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #60</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/60.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by delgermurun** [comment]
Hi @mattp95,

Sorry, I think I don't understand your question fully. But let me try to answer anyway.

Our code is open but when you run it certain API endpoints require a user to have logged in or to have specific permissions. Code is public but when you run it API endpoint are not.

I don't know what OpenAPI is so I couldn't comment on it.

I hope I answered your question, at least some of it. Thanks!
