### ISSUE TITLE
code base structure and server code

### ISSUE THREAD

**Issue by jaylensoeur** [async-labs/saas#61]
I find it very common in the Node community write code this way. There is nothing wrong with it, however, in the last few years I have moved away from it and started using clean architecture.

In the example below the code base uses OOP - you can however easily replace it with functional paradigm. Try to ignore the paradigm used, look at the structure which i think works well. The drawback is a bit more boiler plate code though.

This is an example:
https://github.com/jaylensoeur/momenton-task

So my question is:
Is this too complicated or overkill? and what is your opinion on the example I've linked.

Thanks

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #61</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/61.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by delgermurun** [comment]
https://github.com/jaylensoeur/momenton-task is no longer exists (or not public anymore), so closing this issue.
