### ISSUE TITLE
User cannot delete their account and data

### ISSUE THREAD

**Issue by marcusbelcher** [async-labs/saas#75]
Hi all,

Great demo, love what you're doing. I have an issue around compliance. I have built something similar a few times and I hope by raising this now it saves you a headache down the line. 

I am unable to manage user data inline with GDPR. Typically this equates to:
- Delete user
- Request all data linked to user
- [optional] Obfuscation on linked items. I.E. If a user is deleted but they posted an image, and this image is owned by the company not the user, the username/id link is obfuscated when the user deletes their account. This allows the image to exist and the user to delete their account. This is pretty tedious and not recommended unless deleting a user breaks areas of the application. 

I know it is early stages but I would recommend adding in an "accept EULA" model which the user can see in the account area. And allow GA tracking to be optional: 
- EULA and privacy policy is mission
- GA tracking being optional 

I see the above as a requirement for a B2B template. 

Best,

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #75</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/75.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by tima101** [comment]
@marcusbelcher Thank you for you suggestion. It's a good idea. Ultimately a web developer who uses this open-source project should add these features to be compliant.

We were planning on creating a small library of custom features such as two-factor authentication, PostgreSQL, admin app (and more) **after** we release book for SaaS boilerplate later this summer.

`Delete user` and `Request all data linked to user` will be part of that library of custom features. We would need to take these feature from our current SaaS product (Async) and adopt them for SaaS boilerplate.
