### ISSUE TITLE
Postgres Support

### ISSUE THREAD

**Issue by victorray84** [async-labs/saas#79]
Hi, 
  I’ve purchased your first book. I like the book. Do you have a any plan to support Postgres? 

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #79</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/79.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by tima101** [comment]
@victorray84 Hi. No plans to do it inside the second book. 

But we are discussing publishing code for popular features like PostgreSQL. Optimistically, at the end of this year.

**Comment by victorray84** [comment]
@tima101 Thanks for replying. I'm waiting for Postgres stuff.

**Comment by victorray84** [comment]
@tima101 Can I fork the project and convert it into Postgres?

**Comment by tima101** [comment]
@victorray84 Sure!
