### ISSUE TITLE
custom <App>

### ISSUE THREAD

**Issue by tima101** [async-labs/saas#8]
Create custom <App>, retire `withLayout`

**Comment by tima101** [comment]
@klyburke Would you please test out signup flow and load all pages?

**Comment by klyburke** [comment]
@tima101 I tested the full flow for a new account (including invite Team Member and create a Discussion). All works for me.

The text in the Subscribe button was not clear to me, so I made a small update: f09497544589fc6831f52150782dc565d2bba3b9
