### ISSUE TITLE
Progress bar for light/dark theme switch

### ISSUE THREAD

**Issue by klyburke** [async-labs/saas#82]
There is a small delay when switching between the light and dark themes. It would be nice to have a progress bar to indicate that the switch is taking place; otherwise, users may think the feature is not working.

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #82</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/82.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by tima101** [comment]
@klyburke done in #139 Thanks for reporting.

**Comment by klyburke** [comment]
looks good, thanks!
