### ISSUE TITLE
Ch. 1 - book/1-end/app, I think it was supposed to be book/1-begin/app

### ISSUE THREAD

**Issue by mrhanson3** [async-labs/saas#90]
"These rules are listed in a tsconfig.json file. Go to book/1-end/app and create tsconfig.json with following content:"

This is already in the book/1-end/app, so I think it was supposed to say book/1-begin/app. 

Do y'all care about this type of input? If not, no worries. 

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #90</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/90.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by ElijahElrod** [comment]
This happens multiple times throughout chapter 2, In chapter two: 'Inside book/2-end/app/lib/, create a theme.ts file with following content:',
'Add all three changes to your current book/2-end/app/pages/_app.tsx. You will get:'

**Comment by klyburke** [comment]
Thank you @mrhanson3 and @ElijahElrod! I reviewed those 3 items and corrected them.

@ElijahElrod, I confirm the multiple instances in chapter 2. I went through chapter 2 and corrected all places where we should have `-begin` instead of `-end`. I'll check through the other chapters as well.

@mrhanson3 we do appreciate this feedback!

**Comment by klyburke** [comment]
@mrhanson3 @ElijahElrod  Thanks again for bringing up this issue. I corrected all cases in the book where we wrote `-end/` but meant `-begin/`
