### ISSUE TITLE
Chapter 3, this code is missing an } at the end.

### ISSUE THREAD

**Issue by mrhanson3** [async-labs/saas#92]
![Screen Shot 2020-08-04 at 12 46 23 PM](https://user-images.githubusercontent.com/20564536/89321143-84aed700-d650-11ea-8813-182a60e88f2c.png)

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #92</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/92.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by mrhanson3** [comment]
It's missing in the book.

**Comment by klyburke** [comment]
Thanks! Fixed
