### ISSUE TITLE
Ch. 3 hardcoded not harcoded :)

### ISSUE THREAD

**Issue by mrhanson3** [async-labs/saas#93]
![Screen Shot 2020-08-04 at 2 19 24 PM](https://user-images.githubusercontent.com/20564536/89329918-829f4500-d65d-11ea-916c-6cca53059692.png)

<p/><hr/><details>
      <summary>Click to see <b>Hill for issue #93</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/93.png" alt="Single issue hill" class="s3-image" width="100%" /></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image" width="100%" /></div></details>
      
created by [Async](https://async-await.com/)

**Comment by klyburke** [comment]
Thanks! Fixed
