### ISSUE TITLE
yarn install bcrypt issue

### ISSUE THREAD

**Issue by shubhamBlockstart** [async-labs/saas#94]
When i use yarn install then i am getting issues . not able to resolve 

![image](https://user-images.githubusercontent.com/68530162/89726342-4beb7500-da37-11ea-940b-1884026e991f.png)
![image](https://user-images.githubusercontent.com/68530162/89726352-5d348180-da37-11ea-83cf-80601eb33140.png)
![image](https://user-images.githubusercontent.com/68530162/89726356-658cbc80-da37-11ea-8c3b-31bb2f40bc3e.png)
![image](https://user-images.githubusercontent.com/68530162/89726359-6d4c6100-da37-11ea-8718-3d0d869e4c59.png)
![image](https://user-images.githubusercontent.com/68530162/89726360-76d5c900-da37-11ea-915d-4ea3194b2e47.png)

**Comment by tima101** [comment]
@shubhamBlockstart Did you figure it out?
