### ISSUE TITLE
There are only 10 chapters

### ISSUE THREAD

**Issue by mrhanson3** [async-labs/saas#98]
End of chapter 1 in environmental variables.

"In Chapter 13, you will learn to deploy the app and api projects to Heroku and AWS Elastic Beanstalk. Once the projects are deployed, you will be able to update environmental variables without redeploying your projects."

**Comment by mrhanson3** [comment]
Further down, "The above is a full list of env vars we will have by the end of Chapter 13. You will add values as you progress through the book."

**Comment by klyburke** [comment]
@mrhanson3 Thanks! Yes, we ended up reorganizing to 10 Chapters. I fixed all instances where we meant to write Chapter 10.
